### ISSUE TITLE
Uncaught Type error

### ISSUE THREAD

**Issue by adamlith** [eQueline/eQueline.github.io#1]
I took a screenshot of the add-on displaying strangely:

[https://imgur.com/mb6HQDe](https://imgur.com/mb6HQDe)

If there is anythting I can do to help you replicate it then let me know. I'm using Crome + Tampermonkey.

**Comment by adamlith** [comment]
An update:

I tried firefox as well, with the same problem:
[https://imgur.com/obPP4ON](https://imgur.com/obPP4ON)

I also realized that everything was working fine, until the "Level to next Ascention Point:" part showed up.

And since it says "TypeError: gameState.ascension is undefined" (which makes sense since I have not ascended yet), I'm guessing that box should maybe not be displayed until after the first ascension? or at least treat gameState.ascension as zero if not defined.

**Comment by adamlith** [comment]
And this is my savefile:

U2FsdGVkX1/YdfNm0mAHkawcja5Bzuk0TTNXL9Qi/l2v9LEdCptjrwRdUlWO6ZW5ebMCRc9fnrFzUi+8+fhoW2Z7KxaQHFkKSrtNLUy6SgISg8vok+zMBzdZrYHMj//fTyG8exUDcZWwDqEq4ANLgynPsmhZ43HQhbMnT8Gf712AqQqb/EHBKzYz0DMxnah5/E6u1E4H46jk1mE0eEh1TKcmMKUVqqr01wNCtPqoNWlabHK5XkZueL2lPc8oYKz+WsUuAEdrin5FvvfRqU5+xk6PxWcLXBQaeBZnorywMV3r1eW7aoRJMpZyEL7G/LQSDiPDi/SBP/BS5xhA8nrPCO0R92RMJvDaYz4X2yWSRzIQIP4k2/w6zDyJRYdWyHuHPYywQVJBiuLna8+aUQmxwkpyWymvh5J6/FibBu6uxwjte0d+fzFIeSseobpuh6bY0vATJY9Ph4OzISj681KtFALwdU5zo07APyHM9wA4jd4XEWtbKQqFt0ds00YcgNKS4rwbjF8vAjWRcYnkV6gKpED965abzAV6qju5kSgYsNnACyCNKu9e8xtRqKrJTmapgdw6sy8AnLL+syBkDgARud+KaiU2N3mJ0om9Y+Z9VXpTMziPv6v2ENDGjUfMapgbJIciUHcKx2BvkrxgS87wE54yAw5OL/T5xo0+F7rbS0RuRMwptrtfc9A0Q+H4S73bAyLmEdiQDqY5UQFOh3gGcJE1jtTYHIWXKXmvaH/YxumKaVmU+U0cPtM1mg50BQdgcs2WLgb+nT8LkUpuGi6km7sLNNX70u6PiARFYOYMWPCq9eYA7jMxT8O5T/aVN3xpp5X8O2eS0gTUScMK4ur+KfcfhKi+HJdn1OuQFMer2NqD1L4kfQwE+WOxwNdQ/KtN+SDBwlJhxhcbS38AdIlzKyqAZZ4o5vXeHKJHfnaUD0tUEEsjd34ubWXZSf82zA0aiX90EejdAUlDNlc0jDh2rYZjyibhn5UngMBcPJ+QHYZd/a7lsBb19JPA0Pr3eKHeKQ6CwaxoK/aZFXwqCn9z39b3HSU+KsGTXhk+VLeyUxfQ2wfkoccZcX62BluhnxY1yuX4KfWXdVF4ivCGdfC+hHwS1JXv0o5gOBu5uL3U+ZojLQnwPB+/bhTtCozbTYS8/pQ1LAo0FeH9hUKdRItyatUUPKFmkYS7JZY/VEcoqDLjSbP+F32svGo7QQsEDwySlegoTgMyF0Bm+k9ctJfnbeh9sFHn1jAKVhQbqeT+dM1GsahijqZabPw4NVCIblYJRa1Rs0gMxSTWX4x6kcKrBOTRhQ9EarirsPJ1lRhjCSP3YRRnLtop5Z21ZldMjykg/jnKftxUFrzmXV+eQCF0pk/tB+FJS9E+ftdkA+Ni0c4jpzCMyLadh8L8wvbm0hmdZQnAf/SktEAFGExrbZi8a/+K9DzaZqJbkQy6IopAhzemEsRZfMbKH5M+gXzfhJiuOqm9B/tL1gP8a/ydzk9qtNFvMa7nD7GRgWZw8lxROprtiyTIZCy2CrEapyAbOWOXeSkezR9xRAIaFvdLhsTEDeVXbQONYw6akOXmYeRfzUuaPBGsih1C8ub/IhdY9x2Y4DUFWJv4Acuf93CVzX9kY+zmxi3F96/jgnLvmixmMqtVWxOusNSwLc4LjVwr+6QEWUn0pJzI9Vxes7/7sQsEDLfkXS7+gqFHzlIrtsGTpjqqF2Ifhw6u4psB9EL8EvBq0SMVkPRRoifQi2SAaCrP32RrnWsJSSOFCM72mJ4Dx8GqOp4/6K59YqVaI0uMbEnQC7T4fPGZKIEkahySB1rknzdGzQKasg92qfh1iZpfu5WBac0eMgc4kvdR4Lmd1uCnqXW9apGx6mTiOBIfgTGq/qhml6Tojbedzw8BzPR6Q7ks61Hom/mo3yk51en4N0KMpNXbGNAqzIzNZNliIOxxKHGq/OAWgS/Odn8vJW0si4C2GTG7KPmTfbYCbL40hSJwLWEMT33Ya1eykurVgL/P5yBd50T7d0prvVWLVde1lfPRHYyEEL4aWTawCqnto3fVMLPcjlI3/J4W7GjvuFI0dr6zJRsPFg+a+kCg6WGZH33udWcPT6fEHVi72F4poEURodAP7WZ/gVBcJ2gNsB2BMAYQ2MovA30rUAxeaJTcx7FQPFStdgBcDdK375P8MyL/ypKC0YGWd6J+dDiSoqxqMr1UrIkQujvGfVo646EOzNcitABwroJTD0vzZijDJ4M79x+zIqgp2f+OfIO9Mn6VbdUN0lyghpHRaLECwkp5rDxnDnPYKpLSjYSsM/FRl8r3KQgHLOr4DM2tn/l4uZGZHD+e7792qCnxtbbLS8LUoqdg+YAdT3XPCU/0pm18jdpSyGCnRst3g+9OUIpC4PYseMngl4El8P5l+T0cUUWp7P70O30yjO2sjvuU/XFwJat5gu2fPCl8Y5rtoJAzRCb786Di1jcWBfOv+IkamtUwPupMRX2bLsfqKHuGN3vN2SbHjiCuW0OfnVnrnB9tpTMgPLkF6dZxVaSJDGpLanu/FE9TnLBrnH6jVMrH6i1miyOb9K/IJ7GDIHcuQwD9Ma1dpWwkOCsbkttY2I9ztJch4QlA3hkJDfY5mMDjjSuRAUDeZyPp6tscs4jayMS5z4qNakzHE18GaL1EwCYej4Dhzg90F+gihtkXTq4tEKyUgN8XTS6T8q4xIA4CUwrwq3/3fWuROs16O9lcXt6efKjdxJt3hj0Ig2DteinPPmjx5acYYbn+Wq+SAGHzOiz2FRUO8w1SWa43V8NLEWOBaVAEOwvxQ1n4uFzbMpaQoLdSryDj0kgM59bDnrafm9G8G4eIbEqazZts0SnonAV7gWMrZxxV2GR7JaW6p0XzUIZulTZ5gkRmY2WQZuiNiI1Qdn/wm2SQAS8pvfK3THSh7H2pW6/n95eBp+2TDWykFgFlMNsx41nDZdS5Q7zo3O3ZCwPxFrX3lUXXyxiBZdRZM44NljbWaqcryYmtyA4ksqEQ2zSvZHJhQBaW68PM5CGmAof6ry6+y2pbfwSo4DhDwJTHzG60/qu3NCsHFSVELnwg46IPjKlaDkoDoLz1vb/Qd62vZyJKaYjhzkPFioWVQxGp702MPoO8EhoKa0l6jrTivkFBhKVGVMuK3/WaB6AsyhejjU4ddPvswHFXyyNxDLg1rJQ84MlP9pL3fIXD4WAsxSTW5A7K5RLw8JKXiaEODXF4iLB+Gy+4GZ4APoq2mTCpM0hCWq4EUnd+WrKG9R226nvfB1Icu1gJSkAFjJAx9hm8E7/W/KcX3IWz4j558nMzI35dW9hIbZqXRnw4oCRo1EYu7FAeXLWeftNbtgxcWIoaBUQSjhw/Sjkztz0fq2sd+CpVa18VekdJpjGt1Z0k+cXRbQb2KZeW1HdqAztvFQ957qtHzbNPQPR6vBknDOIi0UCO6/xP5YUQZYvh4yrIto8E9tlT7S31t6aF9eC72RTkzMke+o+sEfyI2wVRYJ67kvvkft9aeWdVt4OaU8XgisqIpTTGVsW3aJRW8f5R2loNHyWiy2IS+d2oz/VW1ECqbDYnjBQrFOKPtKhcDPyWNDVXXP/HroiVgqK0gVsjXjUKXnNt5OGDUFNnFZRsWBBl+IxQA0CwD3FqhhvtzRSeRgWntmW1NcSQ74AaSaKH5EUwpjkP6DqKLw3QTkpEvh6H2mqK//adYaaGg4Slh2gPxv0sX3sBz3K6qotBKQTIURla3HpTM9RfI7DaFJiVYRTp94ylFWo+FpKSSUQgUoURgg2muQMtyd5z3Onx92nMKx49EYBQQcA10xUnWVnIRGPJGOvgkDqwMohcinIlO4kfOfWT9trMJSi0gTgq1mULO3VAt8QvX2r3/NMreCt6PZrRsZtah5FgWkClanBYUrltaKvGvU1oHg5W+AiTauZ5Qjk2s8YC06GnXIrVC7woBGnzptGlTdvPPBNx2OqrE4Fd/h0/KifZu8TmiMLK4P8tBPIQGwtyL4zTAB4kJcuk67GkNLyRXbOSfYdUdiL0QkXeFvWPePdwv2ypW2yfjrdv9L2qzGobTpOuJ5SGio3I/dqansupx6RCh9X89lzcAs7RM2szde7L3fNbIdrPHBEM7pOgsOy+ECW4myQq7lLyLQlVOCg/ktSxaMgJC0PphvStBEBruq53PMrTZPl39uvf2Fo3M//PS3oiINmwbIaKuMeT6ys/dMxUroZcGFDWTbIh5Dz5DafUubSJdCjAAeoAIke+v0FkDlTxH5jh3Lz3LR+9nYbeofA5ClQVQQT3efRKV15xR9xFHWDpd0qA0LmF3GmIkvBO2Vc+z+pdDNG2/U+9waSiu+xoIU5DG+//FT1wrLtqFeWnPSqziSjLdlzhj/yyeXt+TQue2AfuC0dUE2Z2BITipOIPM+kP3ne9aQrpg73n3pzYZrek6lieSK7fjaKBtKDywvIRgkYR3kU9RgRfEg/h67LYc+5YyjZgqZ4U6UA3GfSDhEnawAiznhrjWdsDdD32Issp6Ua5bwX//BjASt6bRQT6JwYnTGztPjpfwQSjYHj49mMP4u+j76onXcFCkNYThs8gzXPrDLWhUmz6664BAgGHqfSRmv4CUljlyIJ0HpOQ/KL+b0cGcAb7Y/smwt28G65KZwmPtsbQDYRwt4k9LFNnQprf7zREZnZDOfyllPWx2Sl8Lw1ixcO/RRxmWdozGrsBIu4E5NzAF8o4qagP7kG6Z91VJMqJ8sAKe8LIXrCDzDhX8LZ+2Tx8j3/UNAUvIoB9HVjeKedgH2vdQ8URxvXhxRb/Bqpq/Jd+yTMvrcUXkSyPIq/O9iprh76jtVpuPq+r4nAdTw8lUfcUO7+nQcIsLg/sOvHsN1VfjdT21SG0viz7z04cvRxrax+YjYQ5XPn3R/YFSH8POpFBTNdgh1uylnHUfrna1BuXAqFDWGECxd0/yMrL5ZOMQLbHNfSuSU8gH/emUOh8+j9Un00U+/PchrK91E0mnYEwS/ozR+jz2pjn3RT/fqsbNNvK42XvGAJGWnz46hFu3Zt+GRXVJP2fCDByLzAqQCTJdao8WXmvdBmDiUYJXAUi8gD/xD2mATCRFJab7mpL9D0kzO9dKivtPhTAuf/wsLSRxKYjR5EHyRM8HwDxzEY40u4ghS0AqeU77vWSAyg0Bls7IcT0mhTPSGQVDqe4v/hKF4eA5JzUX1w4qFxTayPUBTKl4t03c9Ns9ATP9fmBLSP/eONo+vx5k3n89Si1ckg08xNg+RdcssACM+fW2Ql6X6VEE3FrkQ3Txyi7OLi6lUEAaObYk47CvgusFbXtt7JeGQx33Ht+i3Z1yHgLrK86sQIObL3slBt0K7XHHliqCrv+SmHkZ7hNA6zoalyyiso6W2YzZVX6DMHgO4EO+tsI/jKejq12/gJFJRVCl4c+y4vIwt1y04RHcYZoVzgP///NkVBR8hO9D7lbLobuthnNTSPLpAO0tCU8kMLgfdWJuMJdqh3J8sIHgfopIsmmrJLfZQu9gaYc1n+577MVyKdBo4KetNkUuJgi8zpa6ue+6xDQEKpUf+Wpj862eg45eqXxgmYzcxA99zenqskDGbwgV6zFHyH0gkFDOvysZANPbLNWkpEQJGak+KZOv9P1U+ohte3Sn9cEmZwZnecq0+xVutnts/zUpoUQyFqZlUGHTKEQqkhJ7PFr+dNjXdPwNCD0AWdkqWEY4miewXm0tKJWi2njVIVI2lI+Yj/gh3tZhxw+zdpIJ62hIOU91OLKw/ezgZEZDsr6KP3vmJy2AILHgu2TEL+RBC40wipu6cf7Y2y02oSFtkcsgrXBTKcFFt3xE4+Z2YFXjZaJz3pbCVnWknyxlaanFm1M3uhGm3qij1vEgfjCiJg7P4I3U+ql0aDz5PYsdzYd89UxjzT0kE00Ul8zn+9QYuciMcL1LrR92roGXOKErQwRVfF/FIeYf5Dz650Y52o5nvJqfLLeL8VeGixJpjB+ZbDBcxCGdZ3q67OGM5muk851tHcqw5bnFAGGiBYYOineXBC/6hLZKeZ9zY66/sn1njmQSWSR/iWT1f0XocsZUkfET0lQqPXb1FN6efJfK1UVSQnaiTw5KffGWY85q8l7pj3dBdDXdM/83+P0kCfZpqknq4HP06nuaS/819QTT6YOwcE4STrKJdprZdBBawYiPe4O0IouSs2YJShwBtOECS7O+nXe6qtl0Da2CdDi2zjzFuLPvOFejSqWFaw6FoHxK6hbXDWNDK8k9YaeUiZ/Mjwj3d7+ecfPmdYnmbbwLpuOKCMxt8SeHD/+Ia5/eXNzxHoNP+FXDwzaicw2/lzhDOOiZZcc1HEM66V5yDbYWsUB+jTdXLzGCZYlFEouzmDYiWxF05mJrTOHu2hZrCvVYi32WEcS7/T19OF2dumb+Cl+v/5ZEK27vTzUuMzTGmWnA64IgoDcRYHqG6MwXHaBuQqRrWJBj1T0iLoA7mIh9rba6UOvQXHS0aDSOYiIrHul/Kc50WqZ2SfCNVyOnttPfXrwH3jiO7j+3KH4AvByKon7FAd7Vj/Wi0keI5DcT54gt53HKPP2Rm3TukGetFFEdMBmPUJGi5593uGTyRJA2gUcXPSJP8ny4APdQXr1dhgH+bPJyqUNjzHCcxMNI4y++5gJXATkh5DRkGIMzfjZgrrVJGu8A9CMSjWcJe9XTyvDD9HySG95NM4wFPd+TO92a1bnQbUOVDA20xL4KmjmwOdGxLNwEX+LoGRpCCGAGpt/F9LMzYdKVtP1pFYQ0h8tJSVcFuRGykCgKg8cEnV4+RsUaNGv2CBmDsxooUEf7z0UR6SwWdtsl61tO736/CmbppSYAN+g6zlfa4hfzTfsobjjVUrxFmoDSQl6DipKlZkpASkM6Qo3ebnjvXwKxSHjoEEqFDjxf3liJrXiZhLF/d8dyAOTqh9QGVPcCA/DpvKeB9eSeOrPN8pLBC11lDHNUT4VNPTwpUQdjzRMYHJdCYRoohdUxOy9PQOyTPCWJUPAnDKe5YJam/QiWAgYJLzcSuwEfIvZeqtFXFs6qwuZILf/3bwPuW+G7Mleg9QCXYTDeqEt6/YkSLK1IZDdmHJGoBt8dCc1NdwrpOxyKfuLgVCk5KzPLpppNML2DlG32aHs7meJDzHXJQavLUdDoVmIeLBbRwHF1LV/EVl1s+orwYGM/hDiULY/zga4pvRhuaC/IivixXdKIckv3JVphc/yFlLyJInwU0zn6oc6+48T8+W/bC7Iq6shEvZNL2kvMtaLeyurXsy+DZgKJboN1f+RhpB7Rq+0xGdEpmicY6re9KEkwmEh45VMZBVjD59Xc9n+uhJd2ULVSfXy3JjgKzJnS1GjiH64nyFC6jTWzRQcYcTRXAKe/RlGy13TIA2Cpyi5izAdz/izcSdnK4OOQ08LIWq4DNBITz8i3MySnetdLbsh466rTpTaZNWNFDJixzz8c1Q8vsi4pMUr53vz/ybRw6d9jB7rTZoNB0UDOHGrC1BZG8gew+idjyMrhaz2/Bmc6l2eg6Sj3EaxwuyQo4ek668SpHWly3qu+vH5ic/ADr85EetpmT0h1ECF54+vwR/oQRW8MVUVPtW1S5LeQ/Mf4sZHfMM9oY8aIAIncvERW6/tsG+iSOEYF8HV5t9jk9keEPa8TMe7e2hxFnYaAiqjyxcGW4zHO4jHwJWjAKGVQIJVcErCDqTzFJM+qyoc28i+gYPAZTDbqOMelqi6tlEq1GZPB6R3HxXsOwzSxf8bRDVPu4Zm+F3YQ62ESTgvN5Ko9SnI+nuLE4m52gIsvMKuJUkb1xbKwn4M9jfCKURwPmFORNkJf+gSzd4LCNrt9jM+SAf+m7GOfQ8xlM2j1Xj3LhSDQkIUSM+iHh6LPsBQIdM1IRMddjrR/TxCYjDndL1H4c6Ttzni9OjyBwaPdTyBHnujq+zR+EH4YhbnOTdeD/+axkblUdRB+uxAbWexwDS7YUv1IvNw/rrSbQjqHLHU68HxbuDu7Vvb7grb2ZeX2UAMd1NtCLjzTE5a8nUIhmqJ2yLcUdwkXKkOKg7Y2EF3YMxHHGHoz7R2irAC1rtQI8V0KGDlZ0u9VMUv2yw1L4g2YchaHWB/WuLljuKGJXihAJaEBu0aP8+5yaV5LldgXK5hSD03fjcxqxdzhWvY7ylUXUu8lnGbCPsJgKjaZiHzIkYVQFGAc6Hkadf/+tlrksoj/dQMgfimNUvTTm+1ZI7Vi1RJezBL699DgBnXBVTFDvbINSTA0kuI8UUbOzYxiSdwwoLzBccDE5iqOqi6wBb+wK301199t5AoRWKpBJdl2gG59iZiJBXxHpLafHwKHAcCf12gAEon/w9af80rU7AwRZQ7COBvEaDKUw4Eto90bP9KVLE1S2duR3oornSQ1Gr5OrJRMIN3iFapdsNJ0fyEI5/hqHcmarabm+oAcn2o+9XZQCr8JBN0HGBwLtpb0KRVVMQnL9Xq6wBS7hoSu4a4Cc9PEho4QbNAFuuXFna03O8R4VL7SQh2PoOBTE7ZCp8vLbuTtikg5/nmIAfXPfJheDAFCjJ4iDDR0okoePSjanf06kHEx7nZWkZ89o91P8OQaiBqYwOTB4XH6K+MZkNGTPNUO8JQquYTzsCt4Yx6BOkALZFg746sM1FkVB9qzbAFvJ0pgGpkPftk2LuGldXTYFINbx8ItpN60c/r0nVSUrpGqTnOq19dGgO+lOOnW3AMBwLuj4Kdoq2DXW5xzIrFkIMKeLciLBB5cK7S4vFCQyYS5v+MPy3xgRzuA+jMo1JFNIG6+2ubY3nx1vTO1QbAeoSPbVFfPyyHKtgtlhn6Pog8dr++NtawHjzr2yQT2rii6+bVFK1oL8M2hHraaDKRRzVoPOhfsuKSEpb8EdGAYJb+ECUNeR7rEqO+yxFR3DIaFV8o3tlioBq92RaFcZnOZNdHbnfDoZJoEuUM9Pe0MKE0+Oi7A7Q68Gj2UCYy1lnsa2zzhyLgWwvdmwil2D5hO0X8ccMmPKyvpS+WHZBvBEUVNs1gegVCdFYFp98EPbogotRvVExr7glL1taVwbSWD72ZFVqEhf8kNde/k/UgfcU01ftQXlmA3ZwrI6DKOI+jt5xRdHVJPqYJYBLIx+ncRXEGhZH2p900wny7DSupClMW5SBOt7x0YYJjzdmi6AQHYIomCxgv8sPRf8aMLbnRsX+a5rL9B6qehvVxvuRbBvNmmCjCzS9MScOtj/giy2mKrT0dg5gR2fkYgGsF7zpXW3yfEM/gEbxRMr9/WDhkoRBVO2KZ8LqB3FFCR65IVOrPPxV2APNa8tbf1O4QwdaeKYHcR9ulNew4NkAr2DX0LuMaNTyvT6FBUu4nfrjFddSaCF8BiEzUanTMT+RAvhIx6SpDMuP0Ts8TYeLILTPpWiCUFdK+fShQf1UKDTicAt4UbSb8AIUreJsoU0XfBQ==

**Comment by eQueline** [comment]
Fixed
